Update Build.yml
Signed-off-by: Amnesiash <44333360+Amnesiash@users.noreply.github.com>

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -23,28 +23,29 @@ jobs:
     # 下载规则:Mihomo 🧸
     - name: Download mihomo Rules
       run: |
-        mkdir -p ladder-repo/Mihomo/Rules
-        
-        # 直连修正
-        curl -L -o ladder-repo/Mihomo/Rules/Direct.yaml "https://rule.kelee.one/Clash/Direct.yaml"
-      
-        # LAN
-        curl -L -o ladder-repo/Mihomo/Rules/Lan.yaml "https://rule.kelee.one/Clash/Lan.yaml"
-        
-        # 国内流媒体
-        curl -L -o ladder-repo/Mihomo/Rules/ChinaMedia.yaml "https://rule.kelee.one/Clash/ChinaMedia.yaml"
-
-        # 国际流媒体
-        curl -L -o ladder-repo/Mihomo/Rules/GlobalMedia.yaml "https://rule.kelee.one/Clash/GlobalMedia.yaml"
-
-        # 苹果服务
-        curl -L -o ladder-repo/Mihomo/Rules/Apple.yaml "https://rule.kelee.one/Clash/Apple.yaml"
-
-        # 代理列表
-        curl -L -o ladder-repo/Mihomo/Rules/Proxy.yaml "https://rule.kelee.one/Clash/Proxy.yaml"
-
-        # 国内网站
-        curl -L -o ladder-repo/Mihomo/Rules/China.yaml "https://rule.kelee.one/Clash/China.yaml"
+        repo_name=$(basename "$GITHUB_REPOSITORY")
+          if [[ "$repo_name" == "ladder_rules_script" ]]; then
+            echo "Running in Tool repository"
+            mkdir -p ladder-repo/Mihomo/Rules
+            files=(
+                "Direct.yaml https://rule.kelee.one/Clash/Direct.yaml"
+                "Lan.yaml https://rule.kelee.one/Clash/Lan.yaml"
+                "ChinaMedia.yaml https://rule.kelee.one/Clash/ChinaMedia.yaml"
+                "GlobalMedia.yaml https://rule.kelee.one/Clash/GlobalMedia.yaml"
+                "Apple.yaml https://rule.kelee.one/Clash/Apple.yaml"
+                "Proxy.yaml https://rule.kelee.one/Clash/Proxy.yaml"
+                "China.yaml https://rule.kelee.one/Clash/China.yaml"
+              )
+              for file in "${files[@]}"; do
+                  set -- $file
+                  echo "Downloading: $2"
+                  curl -A "Loon/821" -f -L -o "ladder-repo/Mihomo/Rules/$1" "$2" || { echo "Download Failed: $2"; exit 1; }
+              done
+              echo "Files downloaded successfully."
+        else
+            echo "Unknown repository. Please run this script in either Tool or Tool repository."
+            exit 1
+        fi
 
 ######
     - name: Add 和 Commits
