Update Build.yml
Signed-off-by: Amnesiash <44333360+Amnesiash@users.noreply.github.com>

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -18,25 +18,47 @@ jobs:
       with:
         repository: Amnesiash/ladder_rules_script
         path: Tool-repo
-        ref: main  # 确保克隆的是主分支
+        ref: main
 
     - name: Download Rules
       run: |
         mkdir -p Tool-repo/mihomo/Rules
-        # 直连修正
-        curl -L -o Tool-repo/mihomo/Rules/Direct.yaml "https://rule.kelee.one/Clash/Direct.yaml"
-        # LAN
-        curl -L -o Tool-repo/mihomo/Rules/Lan.yaml "https://rule.kelee.one/Clash/Lan.yaml"
-        # 国内流媒体
-        curl -L -o Tool-repo/mihomo/Rules/ChinaMedia.yaml "https://rule.kelee.one/Clash/ChinaMedia.yaml"
-        # 国外流媒体
-        curl -L -o Tool-repo/mihomo/Rules/GlobalMedia.yaml "https://rule.kelee.one/Clash/GlobalMedia.yaml"
-        # 苹果服务
-        curl -L -o Tool-repo/mihomo/Rules/Apple.yaml "https://rule.kelee.one/Clash/Apple.yaml"
-        # 代理列表
-        curl -L -o Tool-repo/mihomo/Rules/Proxy.yaml "https://rule.kelee.one/Clash/Proxy.yaml"
-        # 国内网站
-        curl -L -o Tool-repo/mihomo/Rules/China.yaml "https://rule.kelee.one/Clash/China.yaml"
+        files=(
+            "Direct.yaml https://rule.kelee.one/Clash/Direct.yaml"
+            "Lan.yaml https://rule.kelee.one/Clash/Lan.yaml"
+            "ChinaMedia.yaml https://rule.kelee.one/Clash/ChinaMedia.yaml"
+            "GlobalMedia.yaml https://rule.kelee.one/Clash/GlobalMedia.yaml"
+            "Apple.yaml https://rule.kelee.one/Clash/Apple.yaml"
+            "Proxy.yaml https://rule.kelee.one/Clash/Proxy.yaml"
+            "China.yaml https://rule.kelee.one/Clash/China.yaml"
+        )
+        for file in "${files[@]}"; do
+            set -- $file
+            echo "Downloading: $2"
+            curl -A "Surge iOS/3367" -f -L -o "Tool-repo/mihomo/Rules/$1" "$2" || { echo "Download Failed: $2"; exit 1; }
+            if [ ! -s "Tool-repo/mihomo/Rules/$1" ]; then
+                echo "Downloaded file is empty: $1"
+                exit 1
+            fi
+        done
+        echo "Files downloaded successfully."
+
+    - name: Process Files
+      run: |
+        for file in Tool-repo/mihomo/Rules/*.yaml; do
+          if [ -f "$file" ]; then
+            sed -i -e '/^USER-AGENT/d' "$file"
+            sed -i -e '/^URL-REGEX/d' "$file"
+            sed -i -e '/^AND/d' "$file"
+            file_names=$(basename "$file" .yaml)
+            line_count=$(wc -l < "$file")
+            awk -v fname="$file_names" 'NR==1 {print "# 规则名称: " fname} {print}' "$file" > tmpfile && mv tmpfile "$file"
+            awk -v count="$line_count" 'NR==2 {print "# 规则统计: " count} {print}' "$file" > tmpfile && mv tmpfile "$file"
+            sed -i '2a\\' "$file"
+          else
+            echo "$file not found."
+          fi
+        done
 
     - name: Cleanup Workflow
       uses: Mattraks/delete-workflow-runs@main
